---
# -------------------------------------------------------------------------------------------------
# Site configuration
# -------------------------------------------------------------------------------------------------
site_name: postgrest-helper
site_description: Helper class designed to facilitate interacting with the Supabase PostgREST service.
site_author: Mircea-Pavel Anton
# site_favicon:
# copyright:
theme:
  name: material
  palette:
    scheme: slate
  # logo: assets/logo.png
  # favicon: images/favicon.png
  features:
    - navigation.expand
    - toc.follow
    - navigation.top

# -------------------------------------------------------------------------------------------------
# Repo configuration
# -------------------------------------------------------------------------------------------------
repo_url: https://github.com/Open-Mail-Archive/postgrest-helper
repo_name: 'GitHub'
remote_branch: gh-pages
remote_name: origin

# -------------------------------------------------------------------------------------------------
# Documentation layout
# -------------------------------------------------------------------------------------------------
nav:
  - 'Home': 'index.md'
  - 'Changelog': 'changelog.md'
  - 'License': 'license.md'

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
